### PR TITLE
Pipeline investigation

### PR DESCRIPTION
**Pull request by mattaschmann**
@dwief-usgs 

This pr contains the changes I've made to allow pydrip to be run in the bis-pipeline we have created for ingesting and indexing data as described here: https://code.chs.usgs.gov/fort/bcb/pipeline/docs.  Let me know if you don't have access to that repository.

The gist of all this is this:  I refactored a lot of the business logic out of `drip_pipeline.py` and into a python file `pydrip/bis_pipeline.py`.  This also contains a new method called `process_1` which is a process that is actually run by an aws lambda function in our cloud.  It's outputs will get ingested into our db and indexed into elasticsearch.  The es instance is then fronted with an api, which you can currently view at https://data-beta.usgs.gov/drip/.

I noticed you were outputting 4 csv formatted tables.  Since this all gets indexed as one, I've added a field called `dataset=<table_name>`, so that we can filter between them in elasticsearch.  Three of these tables were the result of getting a subset of the data, which to me looks like it could output even more results if desired.  The process is setup to handle this, you just need to add the desired tables to the list at the top of `bis_pipeline.py`.

You may still run `drip_pipeline.py` directly, and it will still output the 4 csv tables as before.  It will just do it by getting the collected result from `process_1` and splitting it up based on the `dataset` field.  Hopefully this will allow you to test and make changes locally, and see the results exactly as they would appear in the api.

This is a work in progress, but in theory should allow you a way to edit your scripts and ingest them into the api much easier.

If/when you decided to accept this pull request, I'll have to run a pipeline build on my side to get the new code, as currently I am pointing at my forked repository.  This will also have to happen each time you want to update the code.  This process will hopefully be refined in the future.

Let me know if you have any questions or concerns.

CC: @aulenbac  @skybristol

### CODE REVIEW

**Comment by dwief-usgs** [comment]
@mattaschmann @aulenbac  plan to look at this the next few days.  thanks for the work on this.  I will likely be noting things in comments as I go... lots of commits to sift through and need to get myself back up to speed.

Notes:

- Update description for response body under api/v1
- fulldataseet url does not work: Access denied

**Comment by mattaschmann** [comment]
@dwief-usgs 
The no access to https://code.chs.usgs.gov/fort/bcb/pipeline/docs is noted.  That is not ideal as we want potential developers to have access to it without needing to give them direct access.  I'll look into the viability of adding it to a public repository.

**Comment by mattaschmann** [comment]
@dwief-usgs 
I've moved the docs to a github pages site: https://usgs-bis.github.io/pipeline_overview

**Comment by dwief-usgs** [comment]
@mattaschmann  thanks again for the work on this and clearing up some of the issues with documentation.

@aulenbac the API is working and in terms of returning relevant information to feed DRIP except citation information (see next comment)  @mattaschmann  you mentioned that each table could be called but I am having trouble executing that (likely user error but I tried a number of iterations)  are all tables actually available as is or are those just possibilities at this point.  Can one of you provide an example of how I could query the citation table (table name = DamCitations, fields = DamAccessionNumber, CitationDOI, Citation).  thanks

**Comment by mattaschmann** [comment]
@dwief-usgs 

Something like this: https://data-beta.usgs.gov/drip/api/v1/dripdams?pagesize=10&offset=0&q=%7B%22match%22%3A%20%7B%22data.dataset%22%3A%20%22DamCitations%22%7D%7D

**Pull request merged**
